### ISSUE TITLE
add env file.

### ISSUE THREAD

**Issue by ashokpkumar** [ashokpkumar/python_angular#102]
add a env file, this file will contain all the values regarding the environment

add below details and any other details to the env file and change the code to take the value from the env file instead of hardcoded value.

https://github.com/ashokpkumar/python_angular/blob/7b6b52f14858dc2dc65e9d9e14b7afa39718ea76/backend/src/main.py#L31
https://github.com/ashokpkumar/python_angular/blob/7b6b52f14858dc2dc65e9d9e14b7afa39718ea76/backend/src/main.py#L41
https://github.com/ashokpkumar/python_angular/blob/7b6b52f14858dc2dc65e9d9e14b7afa39718ea76/backend/src/entities/database.py#L13

in addition to this add env as local, and env_url and add the localhost URl to this. this should be used whenever we are referencing any URL like the one sent to the user for password reset.
all the URL and env should be stored as a dict , refer stackoverflow for assistance.

**Comment by athakur73** [comment]
code merged
