### ISSUE TITLE
Error in master - bugfix

### ISSUE THREAD

**Issue by ashokpkumar** [ashokpkumar/python_angular#113]
Error in backend code in master, please fix this ASAP

    return dialect.connect(*cargs, **cparams)
  File "C:\Users\I3228\.virtualenvs\backend-a60b8A_6\lib\site-packages\sqlalchemy\engine\default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server does not exist or access denied. (17) (SQLDriverConnect); [08001] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionOpen (Connect()). (53)')
(Background on this error at: http://sqlalche.me/e/14/e3q8)

**Comment by athakur73** [comment]
Deleted extra config file and updated server name

**Comment by athakur73** [comment]
https://github.com/ashokpkumar/python_angular/pull/115
