### ISSUE TITLE
add field validation in both frontend and backend

### ISSUE THREAD

**Issue by ashokpkumar** [ashokpkumar/python_angular#19]
Currently the fileds in frontend and fields in backend does not has any validation and we can give numbers inplace of string and string inplace of email etc

Add validation in frontend based on below criteria
Add employee:
    emp_id>string, character limit 6 characters
    email> string, add email validations(available in angular)
    first_name>string shoul;d not have any integer
    last_name>string should not have any integer
    sur_name>string should not have any integer
    initial>string max characters 5
    salutation>string should be a dropdown (Mr, Mrs, Miss, Mrs)
    project_code>string no limits
    geography:string no limits
    dept:string dropdown values from set of values(Digital, etc)

    emp_start_date:string>dropdown with date picker
    emp_last_working_date:string> remove this field
    emp_project_assigned_date:string> drop down with date picker
    emp_project_end_date:string>remove this field

    employment_status:string> dropdown with values(New joinee, Trainee Intern,)
   Designation: String> 
    manager_name:string
    manager_dept:string dropdown (Digital, etc)
    resource_status:string 
    delivery_type:string
    additional_allocation:string
    skills:string
    roles:string

**Comment by ashokpkumar** [comment]
completed

**Comment by de-epak** [comment]
Required changes is on Final RK comit-https://github.com/ashokpkumar/python_angular/pull/31
