### ISSUE TITLE
add project in the time submission window-Backend and Frontend changes

### ISSUE THREAD

**Issue by ashokpkumar** [ashokpkumar/python_angular#39]
Currently the time submission window doesnt capture any project specific info and only acts as a attendance capturing tool.

Add a select option which shows the list of projects the user is assigned to.
this select option is enabled only if the time type is selected anything apart from leave.
this select option is enabled only if hte time type is like regular, wfh.

the user should be able to select one of the projects he is assigned to, the select option will show the list of projects he is assigned to. along with a list, add a option called bench,

this options should be captured and added to the DB in a new column called project_info in the time submissions as well as time master list.

**Comment by de-epak** [comment]
only backend-https://github.com/ashokpkumar/python_angular/pull/53/files
