### ISSUE TITLE
add timesheet table and API endpoint

### ISSUE THREAD

**Issue by ashokpkumar** [ashokpkumar/python_angular#4]
create a table called "time_master", this holds the monthly data for each employee
column names empid, month, year,timedata
column timedata is a dict data for the month for each dates like [01/03/2021:[wfh,8],02/03/2021:[wfh,8] ]
the format for each data would be [date1:[time_type,time],date2:[time_type,time],date3:[time_type,time]........date31:[time_type,time]]
time_type would be the attendance type like wfh, regular, casual_leave, sick_leave, annual_leave so this would include both the attendance and leave information for the users in one place

API:
<<<<<< Do not work on the below req## create only the table alone
_one endpoint to submit time, this would capture the date range/single date value and check if the data is already available for this date/daterange, if the data is not present, add the date and time information in this format date1:[time_type,time] in the list "timedata" for that particular employee.

split into two functions where it checks if there is a end date, if there is end date it will perform the operation for all the dates else just for the one date._

**Comment by athakur73** [comment]
creating API end point

**Comment by ashokpkumar** [comment]
Closed as this changes are done
