### ISSUE TITLE
submit time info-User-Table creation

### ISSUE THREAD

**Issue by ashokpkumar** [ashokpkumar/python_angular#5]
1. create a table tablename->"time_submissions" which stores the time data being submitted by the user temporarily from_date, to_date, user_name, manager_name, time_type, submission_id(submission id would be a combination of fromdate_todate_user_manager) status(status type would be awaiting review, rejected)

2. create post endpoint which takes the input from the users->from_date, to_date, user_name, manager_name, time_type and hours and store it in the table "time_submissions"

3. create a post end point which takes the input as manager name and returns all the entries for the manager name from the table "time_submissions"

4. create a post endpoint which takes the input as submissionID, review_status and perform action based on the review status
   a.)if review status is true, this means its approved and it will approve the time data(by approving, it takes the data from the temp table and adds the time information to the table "time_master" for the particular user for the particular month.
   b.)if the review status if false,  this means its rejected and will put the status as rejected and will keep in the table itself

**Comment by ashokpkumar** [comment]
changes done, hence closing

**Comment by de-epak** [comment]
https://github.com/ashokpkumar/python_angular/pull/24
