### ISSUE TITLE
make [project_code] in employee column a list-Backend

### ISSUE THREAD

**Issue by ashokpkumar** [ashokpkumar/python_angular#55]
[project_code] column in employee table is currently a string and the logic will replace the existing value if overwritten.

change the column to accomodate a list of values this will help us capture the project code wise time in the frontend
change the logic to add project to resource to add the project code to the list of existing list instead of replacing the existing content.

you can copy the logic from here:     https://github.com/ashokpkumar/python_angular/blob/090fa578d5f94cf2a0b6dcde301f03a08a3f2ada/backend/src/main.py#L363

Once this is done, change the "timeInfo.project_id" select values to flow from the list of projects assigned to the employee in the project code column. this is currently hardcoded.

**Comment by de-epak** [comment]
Reviewed and Merged

**Comment by de-epak** [comment]
https://github.com/ashokpkumar/python_angular/pull/93
