### ISSUE TITLE
add sample data for all table-Backend

### ISSUE THREAD

**Issue by ashokpkumar** [ashokpkumar/python_angular#60]
add sample data to all tables except time master

Like this :
https://github.com/ashokpkumar/python_angular/blob/d189813669a0cafba2955afd9de700fcb3b65c8f/backend/src/entities/sample_data.py#L5

and add functions to add the list data to the tables. this will contain all permutation combination for names, roles etc

for authUser table, add pseudo names like manager, lead, sales_lead, vicepresident, admin to reproduces roles functionality,

this will be used to show/hide functionality based on the roles.

**Comment by de-epak** [comment]
Most updated PR-https://github.com/ashokpkumar/python_angular/pull/95
