### ISSUE TITLE
add roles based view function-frontend and backend

### ISSUE THREAD

**Issue by ashokpkumar** [ashokpkumar/python_angular#62]
currently we are exposing all the functionalities to the frontend, we need to add checks to show content as per the roles

>like admin should only view options of override,
>manager should only view options to add employee
>employee can only view timesheet and personal information summary- this will look odd as this will be the only data shown to employee and will look small, but we will add more content to this like payslip etc.
>sales team can see the add project option.

**Frontend:**
refer the attached document for the application requirement and add checks like ngif if the user has admin in the roles or user has manager in the roles etc.

for now use a hardcoded value by setting the cookie in the login functionality here.https://github.com/ashokpkumar/python_angular/blob/d189813669a0cafba2955afd9de700fcb3b65c8f/frontend/frontend/src/app/login/login.component.ts#L28

we are setting this.forgetpass =false by default, 
set the cookie value like this to test for now. we will return the value from backend later.

**Comment by athakur73** [comment]
code merged
