### ISSUE TITLE
Complete the Password Reset Cycle-Frontend

### ISSUE THREAD

**Issue by ashokpkumar** [ashokpkumar/python_angular#85]
Scenario:
Once the user Clicks on the forgot password Cycle, a window should open which asks for the username or email address,
Then once a user input the username or emailaddress, an email will be sent to the user with the link to reset the password.

The user has to click on the password reset link and this will land to a page which contains username, new_password and Confirm password, Once the user provided the new password and confirm password, the page should accept and store the new password in the system and then refresh the page telling that the password reset is success and provide the link to the login page to login and continue.

Once the user click on the login link, it should land to the login page and then he should continue with login as usual.

Frontend:
Create a new page to enter the email/username to send the password reset link to the user. Rest all the frontend are available already.
This page should have just one input box which takes username/email as input and then a button to submit. Once the user click on the button, it should accept the input and then send it to the API which will be written in the below request. 

once the API returns a 200, the page should hide all the elements and show a message "Password reset link is sent to the registered email. please check your email inbox to continue"

password reset page is available already and the related API to add the new password to the db is already available.

**Comment by athakur73** [comment]
Completed. code merged
