### ISSUE TITLE
Complete the Password Reset Cycle-Complete-Do not Pick this 

### ISSUE THREAD

**Issue by ashokpkumar** [ashokpkumar/python_angular#89]
Scenario:
Once the user Clicks on the forgot password Cycle, a window should open which asks for the username or email address,
Then once a user input the username or emailaddress, an email will be sent to the user with the link to reset the password.

The user has to click on the password reset link and this will land to a page which contains username, new_password and Confirm password, Once the user provided the new password and confirm password, the page should accept and store the new password in the system and then refresh the page telling that the password reset is success and provide the link to the login page to login and continue.

Once the user click on the login link, it should land to the login page and then he should continue with login as usual.

Frontend:
Create a new page to enter the email/username to send the password reset link to the user. Rest all the frontend are available already.
This page should have just one input box which takes username/email as input and then a button to submit. Once the user click on the button, it should accept the input and then send it to the API which will be written in the below request. 

once the API returns a 200, the page should hide all the elements and show a message "Password reset link is sent to the registered email. please check your email inbox to continue"

password reset page is available already and the related API to add the new password to the db is already available.

Backend:
DB: Create a new table to store the password reset details table_name: forget_pass
Columns:
user_id, email_address, reset_token, create_date

API:
1. forgot_pass_create_token: 
This api will take the user_id/email as input and check if the user exist in auth and employee table.
If yes, then then the API will create a token and store in the forget_pass table. The token should be created as similar way to the one we created in login token, the inputs should be user_id and datetime with which the toekn is created. Also send the email module to send and email to the user with a message and the reset link as below with token as the end.

https://localhost:4200/reset_pass/123123123123123

2. reset_pass(get)
this takes the url parameter (token) as input and check if the token belong to table( forget_pass) and is still valid( for now keep validity as 48 hours) if yes, then redirect the user to the password reset page. 
password reset page is available already and the related API to add the new password to the db is already available. Just change the login in the password reset api to remove the entry from the forget_pass table once the new password is set.

**Comment by athakur73** [comment]
Completed. code merged
